Mention table keys in documentation
red-blox/zap pull request #119
Opened 2024-07-02 09:48 UTC by Ketasaja

Why is this worth mentioning? Tables are everything to Luau, `RemoteEvent` serialization doesn't respect them, and Zap does.

2024-07-02 09:50 UTC, sasial-dev commented
I'm not sure if we want to encourage some of those behaviors tbh. Things like holey arrays are bad practice.

2024-07-02 09:56 UTC, Ketasaja commented
I wouldn't encourage holey arrays either, but I think using numbers as identifier keys is idiomatic (like Roblox user identifiers), and if you're ever sending identifier `1` through a `RemoteEvent`, you accidentally made an "array".

I'm fine with this PR being rejected though.

2024-07-02 19:36 UTC, jackdotink commented
I'm fine with this general idea being listed in the docs, but I would rephrase it to something like "Extended Type Support" and "Zap supports far more types than Remote serialization does. Maps with numbers and instances as keys is a good example."

2024-07-15 07:31 UTC, sasial-dev requested changes
Just following this up! :)
Please review @jackdotink's comments

2024-07-22 05:29 UTC, sasial-dev approved these changes
LGTM!

2024-07-22 05:29 UTC, merged