Add tuples
red-blox/zap pull request #140
Opened 2024-11-24 01:45 UTC by nezuo

TODO:
- [ ] TypeScript output
- [ ] Tooling output
- [ ] Code cleanup?
- [ ] Docs

2024-11-24 03:52 UTC, nezuo commented
PR is ready for review.

2024-11-25 06:36 UTC, sasial-dev requested changes
Thank you for this!
It pretty much looks good to me, but it would be nice to address these minor things :)

2024-11-25 06:36 UTC, sasial-dev commented on zap/src/irgen/des.rs
> +			self.push_ty(ty, var);
This is... awkward.
Let's instead add an `nsuffix` method to the `Var` impl (see `var.nindex` as a good example).
And then we can do something like
```suggestion
			self.push_ty(ty, var.nsuffix(i + 1));
```

2024-11-25 06:36 UTC, sasial-dev commented on zap/src/irgen/ser.rs
> +			self.push_ty(ty, var);
Same comment as above

2024-11-25 06:36 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +				})
If you apply my comment above:
```suggestion
				.map(|i| format!("value{}", i))
```

2024-11-25 06:36 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +			"value".to_string()
```suggestion
			"value1".to_string()
```

2024-11-25 06:36 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +				if i == 0 { "".to_string() } else { (i + 1).to_string() }
```suggestion
				(i + 1).to_string()
```

2024-11-25 06:36 UTC, sasial-dev commented on zap/src/output/typescript/client.rs
> +				if i > 0 { (i + 1).to_string() } else { "".to_string() },
```suggestion
				(i + 1).to_string(),
```

2024-11-25 06:36 UTC, sasial-dev commented on zap/src/output/typescript/client.rs
> +	fn push_parameters(&mut self, types: &[Ty]) {
This function should maybe be in `mod.rs`?

2024-11-25 06:36 UTC, sasial-dev commented on zap/src/output/luau/server.rs
> +				})
```suggestion
				.map(|i| format!("rets{}", i))
```

2024-11-25 06:36 UTC, sasial-dev commented on zap/src/output/luau/server.rs
> +				if i == 0 { "".to_string() } else { (i + 1).to_string() }
```suggestion
				(i + 1).to_string()
```

2024-11-26 23:34 UTC, sasial-dev approved these changes
LGTM - thank you!

2024-11-26 23:35 UTC, merged