Optimize event ids by splitting them up by server/client and reliable/unreliable
red-blox/zap pull request #143
Opened 2024-12-31 19:07 UTC by nezuo

Currently, all events and functions share event ids in the same pool. This is unnecessary and optimizing it will allow for more events/functions before needing to increase the bytes required for the event id.

To give an example, reliable events and functions are never sent through the unreliable remote. This means we can have separate pools of ids for reliable and unreliable.

2024-12-31 19:12 UTC, nezuo commented
Event ids used to start at `1` instead of `0`. I'm not sure why this was the case, let me know if I'm missing something!

2025-01-06 02:49 UTC, jackdotink commented on zap/src/config.rs
> +	}
why are we doing this instead of having separate reliable and unreliable counts?

2025-01-06 06:43 UTC, nezuo commented on zap/src/config.rs
> +	}
This allows for more events before increasing the ids. Imagine 256 reliable client to server events and 256 reliable server to client events. With how I've done it, that only needs a u8. If we combined them, it would need a u16. It's possible to separate them because the events are one-way.

I might have misunderstood the question though.

2025-01-06 21:24 UTC, jackdotink commented on zap/src/config.rs
> +	}
Yeah I was asking why not have `server_reliable` and `server_unreliable` counters, and the respective client counters too

2025-01-06 21:24 UTC, jackdotink commented on zap/src/config.rs
> +	}
I think that would be better than putting them into one list and then iterating over it each time

2025-01-07 17:45 UTC, jackdotink approved these changes

2025-01-15 03:49 UTC, sasial-dev commented
@nezuo apologies - could you please fix the merge conflicts in your PR?

2025-01-15 09:00 UTC, sasial-dev requested changes
Sorry for the delay in reviewing this! This looks pretty good - I just have a few comments before we can merge this in :)

2025-01-15 09:00 UTC, sasial-dev commented on zap/src/parser/convert.rs
> +				},
This counts for all, not just unreliable IDs

2025-01-15 09:00 UTC, sasial-dev commented on zap/src/parser/convert.rs
> +			} else if max.is_none_or(|max| max >= max_unreliable_size) {
Have to double check the behavior here, is the packet dropped at 900 (`>`) or 901 (`>=`)?

2025-01-15 17:37 UTC, nezuo commented on zap/src/parser/convert.rs
> +			} else if max.is_none_or(|max| max >= max_unreliable_size) {
This functionality should be equivalent as I used rust-analyzer to automatically fix it. It was being linted by clippy. It seems like it should be `>` but that's not what it was doing previously.

2025-01-15 23:57 UTC, sasial-dev approved these changes
Thank you!

2025-01-15 23:58 UTC, merged