Add manual event loop option
red-blox/zap pull request #47
Opened 2024-01-02 02:01 UTC by nezuo

Adds a `manual_event_loop` option which exports a `send_events` function when `true`. This is useful when the user can schedule `send_events` after all their other code that runs in the frame.

2024-01-02 02:02 UTC, nezuo commented
Making this a draft because it doesn't have documentation.

2024-01-02 02:20 UTC, sasial-dev requested changes
Some initial comments

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +		self.push_line("");
```suggestion
		self.push("\n");
```

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +		};
There's no need to branch twice. Let's remove this section.

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +			let send_events = self.config.casing.with("SendEvents", "sendEvents", "send_events");
Let's move Line 77 here

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +			self.push_line(&format!("RunService.Heartbeat:Connect(function({delta_time})"));
And hardcode in deltatime here
```suggestion
			self.push_line(&format!("RunService.Heartbeat:Connect(function(dt)"));
```

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +	end"#,
This should be split up into mutiple lines w. `self.push_line` and `self.indent` etc. Use the rest of the file as an example.

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +		self.push_line("");
```suggestion
		self.push("\n");
```

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/client.rs
> +		}
Let's not branch here and move it back up to inside the `if` statement.

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/server.rs
> +	end"#,
Same comments as for the client here - split this into `self.push_line`, `self.indent` etc

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/server.rs
> +		self.push_line("");
```suggestion
		self.push("\n");
```

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/server.rs
> +		self.push_line("");
```suggestion
		self.push("\n");
```

2024-01-02 02:20 UTC, sasial-dev commented on zap/src/output/luau/server.rs
> +		}
Same comments as client here - removing this branching and put it in the if statement above.

2024-01-02 23:55 UTC, nezuo commented
Taking this out of draft mode now that there are docs. It still needs a warning about rate limiting the client but I'm not comfortable writing that section since I haven't tested that behavior myself.

2024-01-03 22:45 UTC, sasial-dev approved these changes
LGTM!

2024-01-04 09:30 UTC, jackdotink approved these changes

2024-01-04 09:43 UTC, merged