Compress CFrames using axis-angle representation
red-blox/zap pull request #52
Opened 2024-01-04 06:59 UTC by Tazmondo

Effectively halves the size of CFrames from 12 f32s down to 6 f32s.

Does not deal with non-orthogonal CFrames but this is not really a big issue as discussed in the discord channel.

Please review harshly, I am still not super fluent with Rust so I don't know the common patterns and what good, clean, Rust code looks like.

2024-01-04 07:31 UTC, sasial-dev requested changes
As discussed on Discord:

2024-01-04 07:31 UTC, sasial-dev commented on zap/src/irgen/des.rs
> +						)),
Let's move this over to be an `if`/`else` expression

2024-01-04 20:47 UTC, sasial-dev requested changes
Some initial comments

2024-01-04 20:47 UTC, sasial-dev commented on zap/src/irgen/des.rs
> +				);
```suggestion
				self.push_local(
					"angle",
					Some(Expr::Var(Box::new(Var::from("axisangle").nindex("Magnitude")))),
				);
```

2024-01-04 20:47 UTC, sasial-dev commented on zap/src/output/luau/mod.rs
> +				}
```suggestion
				let items = var.join(", ");
```

2024-01-04 20:51 UTC, Tazmondo commented on zap/src/irgen/des.rs
> +				);
Yeah that's a lot cleaner

2024-01-04 21:08 UTC, sasial-dev approved these changes
LGTM!

2024-01-04 21:12 UTC, Tazmondo commented
adding docs don't merge yet

2024-01-05 17:41 UTC, jackdotink approved these changes

2024-01-05 17:41 UTC, merged